# Support: https://discord.gg/badbones-s-live-chat-182615261403283459
# Github: https://github.com/Crazy-Crew
#
# Issues: https://github.com/Crazy-Crew/CrazyCrates/issues
# Features: https://github.com/Crazy-Crew/CrazyCrates/issues
#
# List of all sounds: https://jd.papermc.io/paper/1.20/org/bukkit/Sound.html
# List of all enchantments: https://jd.papermc.io/paper/1.20/org/bukkit/enchantments/Enchantment.html
root:
  # Whether you want CrazyCrates to shut up or not, This option is ignored by errors.
  verbose_logging: true
  # This option will let you test a different way of picking random numbers. If you have any issues, You can set it back to false.
  use-different-random: false
  # Sends anonymous statistics about how the plugin is used to bstats.org.
  # bstats is a service for plugin developers to find out how the plugin being used,
  # This information helps us figure out how to better improve the plugin.
  toggle_metrics: true
  # The prefix used in commands
  command_prefix: '&8[&bCrazyCrates&8]: '
  # The prefix used in console
  console_prefix: '&8[&bCrazyCrates&8] '
# Settings related to guis.
gui:
  # If /crates should open the main menu. Warning: This will remove the menu button from crate previews.
  toggle: true
  # Inventory settings like size.
  inventory:
    # The name of the gui.
    name: '&b&lCrazy &4&lCrates'
    # The size of the gui. Valid sizes are 9,18,27,36,45
    size: 45
    # The buttons in the gui.
    buttons:
      # The main menu button.
      menu:
        # The item the button should be.
        item: compass
        override:
          # This will disable our current functionality of our main menu button in crate previews.
          # It allows you to override and use a menu of your choice from your plugin using a command.
          toggle: false
          # A list of commands to run when the main menu button is clicked. The override option above has to be set to true.
          list:
            - see %player%
        # The name of the item.
        name: '&7&l>> &c&lMenu &7&l<<'
        # The lore of the item.
        lore:
          - '&7Return to the menu.'
      # The next button.
      next:
        # The item the button should be.
        item: feather
        # The name of the item.
        name: '&6&lNext >>'
        # The lore of the item.
        lore:
          - '&7&lPage: &b{page}'
      # The back button.
      back:
        # The item the button should be.
        item: feather
        # The name of the item.
        name: '&6&l<< Back'
        # The lore of the item.
        lore:
          - '&7&lPage: &b{page}'
      filler:
        # Should the menu should be filled with one type of item?
        toggle: false
        # The item to fill the menu with.
        item: black_stained_glass_pane
        # The name of the item.
        name: ' '
        # The lore of the item.
        lore: []
      customizer:
        # Should the customizer should be enabled?
        toggle: true
        # The items to set to the gui.
        items:
          - 'Slot:1, Item:red_stained_glass_pane, Name: '
          - 'Slot:2, Item:red_stained_glass_pane, Name: '
          - 'Slot:3, Item:red_stained_glass_pane, Name: '
          - 'Slot:4, Item:red_stained_glass_pane, Name: '
          - 'Slot:5, Item:red_stained_glass_pane, Name: '
          - 'Slot:6, Item:red_stained_glass_pane, Name: '
          - 'Slot:7, Item:red_stained_glass_pane, Name: '
          - 'Slot:8, Item:red_stained_glass_pane, Name: '
          - 'Slot:9, Item:red_stained_glass_pane, Name: '
          - 'Slot:37, Item:red_stained_glass_pane, Name: '
          - 'Slot:38, Item:red_stained_glass_pane, Name: '
          - 'Slot:39, Item:red_stained_glass_pane, Name: '
          - 'Slot:40, Item:red_stained_glass_pane, Name: '
          - 'Slot:41, Item:red_stained_glass_pane, Name: '
          - 'Slot:42, Item:red_stained_glass_pane, Name: '
          - 'Slot:43, Item:red_stained_glass_pane, Name: '
          - 'Slot:44, Item:red_stained_glass_pane, Name: '
          - 'Slot:45, Item:red_stained_glass_pane, Name: '
          - 'Slot:10, Item:blue_stained_glass_pane, Name: '
          - 'Slot:19, Item:blue_stained_glass_pane, Name: '
          - 'Slot:28, Item:blue_stained_glass_pane, Name: '
          - 'Slot:18, Item:blue_stained_glass_pane, Name: '
          - 'Slot:27, Item:blue_stained_glass_pane, Name: '
          - 'Slot:36, Item:blue_stained_glass_pane, Name: '
          - 'Slot:11, Item:cyan_STAINED_GLASS_PANE, Name: '
          - 'Slot:13, Item:cyan_STAINED_GLASS_PANE, Name: '
          - 'Slot:15, Item:cyan_STAINED_GLASS_PANE, Name: '
          - 'Slot:25, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:17, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:20, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:21, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:22, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:23, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:24, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:25, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:26, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:29, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:31, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:32, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:33, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:34, Item:CYAN_STAINED_GLASS_PANE, Name: '
          - 'Slot:35, Item:CYAN_STAINED_GLASS_PANE, Name: '
# Settings related to crates.
crate:
  # Whether to show the display item when opening QuickCrate
  quickcrate-display-item: true
  # Logs all crate actions to a .txt file if enabled. It is recommended to delete the file occasionally.
  log-file: false
  # Logs all crate actions to console if enabled.
  log-console: false
  # If crates should knock you back if you have no keys.
  knock-back: true
  # The preview settings.
  preview:
    # If players should be forced to exit out of the preview during /crates reload
    force-exit: false
    # Send a message if they were forced out of the preview.
    send-message: false
  # If a player gets to the menu related to the Prizes gui, Should they be timed out?
  #
  # It will wait 10 seconds and if they already collected 3 prizes, It will only give one prize.
  cosmic-crate-timeout: true
  # Settings related to how keys function.
  keys:
    # Should a physical crate accept virtual keys?
    physical-crate-accepts-virtual-keys: true
    # Should a virtual crate ( /crates ) accept physical keys?
    physical-crate-accepts-physical-keys: true
    # Should a physical crate accept physical keys?
    virtual-crate-accepts-physical-keys: true
    # Settings related to if a player's inventory is not empty.
    inventory-settings:
      # Should the player should be given virtual keys if inventory is not empty? If you leave it as false, All keys will be dropped on the ground.
      give-virtual-keys: false
      # Should the player should be notified when their inventory is not empty?
      send-message: false
    key-sound:
      # Should a sound should be played if they have no key?
      toggle: true
      # The sound to play.
      name: entity_villager_no
  # Settings related to QuadCrate
  quad-crate:
    # How long should the quad crate be active?
    timer: 300
  # What worlds do you want Crates to be disabled in?
  disabled-worlds:
    - world_nether
