name: '${name}'
main: '${group}.CrazyCratesPaper'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

softdepend: [CMI, DecentHolograms, PlaceholderAPI, ItemsAdder, Oraxen]
depend:
  - bLibs